#! /bin/bash
#########################################################################################
#
# Script name: espqldaemon
# Version: 1.0
# Description: start the opera quicklook daemon as an agent in director
#
# start me: agent start -T 1:1 espqldaemon 
#
# Author(s): CFHT OPERA team
# Affiliation: Canada France Hawaii Telescope 
# Location: Hawaii USA
# Date: May/2013
# Contact: opera@cfht.hawaii.edu
# 
# Copyright (C) 2013  Opera Pipeline team, Canada France Hawaii Telescope
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see:
# http://software.cfht.hawaii.edu/licenses
# -or-
# http://www.gnu.org/licenses/gpl-3.0.html
#
#/// \package espqlsaemon
#/// \brief a remote runner for opera
#/// \ingroup scripts
#
#########################################################################################

function usage() {
	echo "$(basename $0): agent start -T 1:1 espqldaemon "
	echo "		start the opera quicklook daemon as an agent in director."
	return 0
}
export COLUMNS=200
sessionhost=`ls -l /h/espadons/.director/sessionhost | sed -e 's/.*-> //' | sed -e 's/\..*//'`
night=$(basename $(pwd))
if (( $# != 0 ))
then
	usage
	exit
fi
opera=$HOME/opera-1.0
echo "rsh maka \"export opera=$HOME/opera-1.0 ; $opera/bin/espqlh --night=$night --director --updatelogbook --upenadir=/data/$sessionhost/espadons/opera/\""
      rsh maka  "export opera=$HOME/opera-1.0 ; $opera/bin/espqlh --night=$night --director --updatelogbook --upenadir=/data/$sessionhost/espadons/opera/"
exit 0
