#! /bin/bash
#########################################################################################
#
# Script name: domacmake
# Version: 1.0
# Description: do a configure and make for xcode
# Author(s): CFHT OPERA team
# Affiliation: Canada France Hawaii Telescope 
# Location: Hawaii USA
# Date: Mar/2012
# Contact: opera@cfht.hawaii.edu
# 
# Copyright (C) 2011  Opera Pipeline team, Canada France Hawaii Telescope
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see:
# http://software.cfht.hawaii.edu/licenses
# -or-
# http://www.gnu.org/licenses/gpl-3.0.html
#
#/// \package domacmake
#/// \brief tdo a configure and make for xcode
#/// \arg make arguments
#/// \ingroup scripts
#
#########################################################################################

cd $HOME/opera-1.0
./configure --enable-LIBPNG=true --prefix=$HOME/opera-1.0
echo "$(MAKE) $@"
/usr/bin/make $@
exit $?
