#! /bin/bash
#########################################################################################
#
# Script name: operafitsverify
# Version: 1.0
# Description: fitsverify the input FITS image only if fitsverify is installed
# Author(s): CFHT OPERA team
# Affiliation: Canada France Hawaii Telescope 
# Location: Hawaii USA
# Date: Aug/2011
# Contact: opera@cfht.hawaii.edu
# 
# Copyright (C) 2011  Opera Pipeline team, Canada France Hawaii Telescope
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see:
# http://software.cfht.hawaii.edu/licenses
# -or-
# http://www.gnu.org/licenses/gpl-3.0.html
#
#/// \package operafitsverify
#/// \brief fitsverify the input FITS image only if fitsverify is installed
#/// \arg FITS image to verify
#/// \ingroup scripts
#/// \defgroup scripts Scripts
#
#########################################################################################

verbose=0
if [[ "`which fitsverify 2>/dev/null`" != "" ]]
then
	if (( $# > 1 ))
	then
		verbose=$1
		shift
	fi
	fitsverify -q -e $1
	errorcode=$?
	if (( $errorcode != 0 ))
	then
		if (( verbose > 0 ))
		then
			fitsverify $1
		fi
	fi
	exit $errorcode
fi
exit 0


