#! /bin/bash
#########################################################################################
#
# Script name: operagetwords
# Version: 1.0
# Description: get words startng at index n count c from a list
# Author(s): CFHT OPERA team
# Affiliation: Canada France Hawaii Telescope 
# Location: Hawaii USA
# Date: Aug/2011
# Contact: opera@cfht.hawaii.edu
# 
# Copyright (C) 2011  Opera Pipeline team, Canada France Hawaii Telescope
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see:
# http://software.cfht.hawaii.edu/licenses
# -or-
# http://www.gnu.org/licenses/gpl-3.0.html
#
#/// \package operagetword
#/// \brief get word n from a list
#/// \arg int index
#/// \arg list of words
#/// \ingroup scripts
#
#########################################################################################

start=$1
shift
count=$1
shift
((j=0))
out=""
while ((j<count))
do
		next=`echo "$start $@" | awk '{ i=$1+1; print $i}'`
		if [[ $next ]]
		then
			if [[ $out ]]
			then
				out="$out $next"
			else
				out="$next"
			fi
		fi
		shift
		((j++))
done
echo -n "$out"
exit
