#! /bin/bash
#########################################################################################
#
# Script name: operalinecount
# Version: 1.0
# Description: count total lines of code
# Author(s): CFHT OPERA team
# Affiliation: Canada France Hawaii Telescope 
# Location: Hawaii USA
# Date: Mar/2012
# Contact: opera@cfht.hawaii.edu
# 
# Copyright (C) 2011  Opera Pipeline team, Canada France Hawaii Telescope
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see:
# http://software.cfht.hawaii.edu/licenses
# -or-
# http://www.gnu.org/licenses/gpl-3.0.html
#
#/// \package operalinecount
#/// \brief total line count in  src and include directories
#/// \arg token
#/// \ingroup scripts
#/// \defgroup scripts Scripts
#
#########################################################################################

# .h .cpp
dirs="$HOME/opera-1.0/test $HOME/opera-1.0/include/ $HOME/opera-1.0/include/libraries/ $HOME/opera-1.0/include/core-espadons/ $HOME/opera-1.0/include/tools/ $HOME/opera-1.0/src/libraries/ $HOME/opera-1.0/src/core-espadons/ $HOME/opera-1.0/src/tools/"
grandtotal=0
for dir in $dirs
do
	cd $dir
	total=`wc -l *.h *.c *.cpp 2>/dev/null | grep total | awk '{print $1}'`
	echo "$dir: $total"
	((grandtotal+=total))
	cd - >/dev/null
done
# scripts, Makefiles
dirs="$HOME/opera-1.0/scripts $HOME/opera-1.0/scripts/espadons $HOME/opera-1.0/harness $HOME/opera-1.0/harness/espadons "
for dir in $dirs
do
	cd $dir
	total=`wc -l * 2>/dev/null | grep total | awk '{print $1}'`
	echo "$dir: $total"
	((grandtotal+=total))
	cd - >/dev/null
done
echo "Grandtotal: `echo $grandtotal | sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta'`" 
exit
