#!/bin/bash
#########################################################################################
#
# Script name: operasplit
# Version: 1.0
# Description: split a reductionlist into parts based on #### delimiters
# Author(s): CFHT OPERA team
# Affiliation: Canada France Hawaii Telescope 
# Location: Hawaii USA
# Date: Aug/2011
# Contact: opera@cfht.hawaii.edu
# 
# Copyright (C) 2011  Opera Pipeline team, Canada France Hawaii Telescope
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see:
# http://software.cfht.hawaii.edu/licenses
# -or-
# http://www.gnu.org/licenses/gpl-3.0.html
#
#/// \package operasplit
#/// \brief split a reductionlist into parts based on #### delimiters
#/// \arg reductionlist filename
#/// \ingroup scripts
#
#########################################################################################
# 
#
if (( $# != 2 ))
then
	echo "usage: operasplit <input reductionlist filename> <output reductionlist filename base> "
	exit
fi
rlistname=$1
olistname=$2
((line=0))
((split=0))
rm -f ${olistname}*
files=`cat <$rlistname`
for f in $files
do
	if [[ "$f" == "##########" ]]
	then
		if (( line > 0 ))
		then
			((split++))
		fi
	else
		echo $f >>${olistname}$split
	fi
	((line++))
done
echo $split
exit
