#!/bin/bash
#########################################################################################
#
# Script name: operaslice
# Version: 1.0
# Description: slice a file, a combo of head and tail
# Author(s): CFHT OPERA team
# Affiliation: Canada France Hawaii Telescope 
# Location: Hawaii USA
# Date: Aug/2011
# Contact: opera@cfht.hawaii.edu
# 
# Copyright (C) 2011  Opera Pipeline team, Canada France Hawaii Telescope
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see:
# http://software.cfht.hawaii.edu/licenses
# -or-
# http://www.gnu.org/licenses/gpl-3.0.html
#
#/// \package operaslice
#/// \brief slice a file, a combo of head and tail
#/// \arg start
#/// \arg count
#/// \arg filename
#/// \ingroup scripts
#
#########################################################################################
# 
#
if (( $# != 3 ))
then
	echo "usage: operaslice <start index> <count> \"<filenames>\""
	exit
fi
((i=$1+$2-1))
((j=$1))
echo "$3" | sed -n "${j},${i}p" | tr '\n' ' '
exit
