#! /bin/bash
#########################################################################################
#
# Script name: operafind
# Version: 1.0
# Description: find a token in a file in the src and include directories
# Author(s): CFHT OPERA team
# Affiliation: Canada France Hawaii Telescope 
# Location: Hawaii USA
# Date: Mar/2012
# Contact: opera@cfht.hawaii.edu
# 
# Copyright (C) 2011  Opera Pipeline team, Canada France Hawaii Telescope
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see:
# http://software.cfht.hawaii.edu/licenses
# -or-
# http://www.gnu.org/licenses/gpl-3.0.html
#
#/// \package operafind
#/// \brief find a token in a file in the src and include directories
#/// \arg token
#/// \ingroup scripts
#
#########################################################################################
if [[ "$1" == "-h" || "$1" == "--help" ]]
then
	echo "usage: $(basename $0) [-c|--case-sensitive] <token to search in sources and includes>"
	exit
fi
casesensitive="i"
if [[ "$1" == "-c" || "$1" == "--case-sensitive" ]]
then
	casesensitive=""
	shift
fi

fgrep -RI${casesensitive}n "$@" test/* | tr '\t' ' '
fgrep -RI${casesensitive}n "$@" include/* | tr '\t' ' '
fgrep -RI${casesensitive}n "$@" src/* | tr '\t' ' '
fgrep -RI${casesensitive}n "$@" harness/* | tr '\t' ' '
exit
